### ISSUE TITLE
No work on Nodejs 4.x in Debian 7

### ISSUE THREAD

**Issue by chetverikov** [seangarner/node-stream-mmmagic#2]
```

module.js:338
    throw err;
    ^

Error: Cannot find module './build/Release/magic'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/my/node_modules/stream-mmmagic/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

```
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! me@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the me@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the me package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls me
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
```

**Comment by seangarner** [comment]
Hi @chetverikov, it looks like you've had an issue building the mmmagic module.  When you did `npm install stream-mmmagic` it will have downloaded the `mmmagic` dependency and built it (because it's a C node module, not pure javascript).

You can check for the output of the build by doing this:
```bash
$ ls node_modules/stream-mmmagic/node_modules/mmmagic/build/Release/
magic.a  magic.node  obj.target  pcre.a
```

Did you see any errors when installing initially?  Don't forget that because it's a C dependency you'll need to install a compiler, etc.  Installing `build-essential` using apt should do it I think.

**Comment by chetverikov** [comment]
Hi @seangarner, the directory node_modules/stream-mmmagic/node_modules/mmmagic/build was empty. I did a manual build and it works now, but previously, everything was done automatically...

**Comment by seangarner** [comment]
Try deleting node_modules then run npm install again to see what happens.

In any event, it'll be something with the mmmagic module instead of this one directly.
